### ISSUE TITLE
encoding and collation

### ISSUE THREAD

**Issue by BarnumD** [blacklabelops/postgres#1]
Just a question.. Couldn't we use the official postgres image instead of using this image but add an environment variable "POSTGRES_INITDB_ARGS=--encoding=UNICODE --lc-collate=C --lc-ctype=C" to achieve the same result as what you have here?

PS: thanks for making this and the jira image available.

**Comment by blacklabelops** [comment]
Yes, you can take the official image and extend it. The new image can put database scripts in the folder `/docker-entrypoint-initdb.d/*`. Those scripts will be executed by the official image.

There is always a limit to this. You will have to reimplemented the whole database creation routine because there is no simple way to change the database encoding and collate afterwards.

Or: Do a pull request on the official image with the changes presented here or proposed by you.

**Comment by blacklabelops** [comment]
Closed because of inactivity.
